const identities = {
  '000': [
    "［蜘蛛巢：食指 父輩］李箱 / The House of Spiders: Index Father Yi Sang",
    "［蜘蛛巢：中指 父輩］奧提斯 / The House of Spiders: Middle Father Outis",
    "［蜘蛛巢：指環 父輩］鴻璐 / The House of Spiders: Ring Father Hong Lu",
    "［蜘蛛巢之刃］良秀] / Blade of the House of Spiders Ryōshū",
    "［指環 野獸派 講解員］羅佳 / The Ring Fauvist Lecturer Rodion",
    "［指環 點描派 學生］奧提斯 / The Ring Pointillist Student Outis",
    "［指環 點描派 學生］李箱 / The Ring Pointillist Student Yi Sang",
    "［食指 代理人 - 綻放E.G.O：代行］堂吉訶德 / The Index Proxy - Effloresced E.G.O::Procuration Don Quixote",
    "［中指 幼兄］希斯克里夫 / Middle Big Brother Heathcliff",
    "［蜘蛛巢：指環 學徒］浮士德 / House of Spiders: Ring Apprentice Faust",
    "［蜘蛛巢：中指 學徒］以實瑪利 / House of Spiders: Middle Apprentice Ishmael",
    "［蜘蛛巢：小指 學徒］辛克萊 / House of Spiders: Pinky Apprentice Sinclair",
    "［食指 傳令：【紙條】］浮士德 / Index Messenger: Slip Faust",
    "［中指 幼妹］堂吉訶德 / Middle Little Sister Don Quixote",
    "［中指 幼弟］辛克萊 / Middle Little Brother Sinclair",
    "［大拇指 東部副卡波 IV］默爾索 / Thumb East Section Capo IV Meursault",
    "［黑獸 未］堂吉訶德 / Heishou Pack Unassigned Don Quixote",
    "［黑獸 巳］格里高爾 / Heishou Pack Snake Branch Gregor",
    "［黑獸 巳］羅佳 / Heishou Pack Snake Branch Rodion",
    "［黑獸 午 魁首］李箱 / Heishou Pack Wu Branch Expert Yi Sang",
    "［黑獸 卯 魁首］浮士德 / Heishou Pack Mao Branch Expert Faust",
    "［黑獸 酉 魁首］希斯克里夫 / Heishou Pack Rooster Branch Expert Heathcliff",
    "［黑獸 卯］奧提斯 / Heishou Pack Mao Branch Outis",
    "［黑獸 卯］良秀 / Heishou Pack Mao Branch Ryōshū",
    "［拉曼查地產 經理］堂吉訶德 / La Manchaland Manager Don Quixote",
    "［拉曼查地產 王子］默爾索 / La Manchaland Prince Meursault",
    "［拉曼查地產 公主］羅佳 / La Manchaland Princess Rodion",
    "［拉曼查地產 神父］格里高爾 / La Manchaland Priest Gregor",
    "［拉曼查地產 理髮師］奧提斯 / Barber of La Manchaland Outis",
    "［腦業公司 E.G.O::哀悼］李箱 / Lobotomy E.G.O::Solemn Lament Yi Sang",
    "［N公司 E.G.O::魔彈］李箱 / N Corp. E.G.O::Magic Bullet Yi Sang",
    "［腦業公司 E.G.O::懊悔］浮士德 / Lobotomy E.G.O::Regret Faust",
    "［LCE E.G.O::炎雀］浮士德 / LCE E.G.O::Ardor Blossom Faust",
    "［腦業公司 E.G.O::提燈］堂吉訶德 / Lobotomy E.G.O::Lantern Don Quixote",
    "［腦業公司 E.G.O::以愛與恨之名］堂吉訶德 / Lobotomy E.G.O::In the Name of Love and Hate Don Quixote",
    "［腦業公司 E.G.O::幽香與孤寂］良秀 / Lobotomy E.G.O::Faint Aroma & Solitude Ryōshū",
    "［腦業公司 E.G.O::大黃蜂【變異】］默爾索 / Lobotomy E.G.O::Hornet (Alteration) Meursault",
    "［腦業公司 E.G.O::狐雨］希斯克里夫 / Lobotomy E.G.O::Fox Rain Heathcliff",
    "［腦業公司 E.G.O::淚刃］羅佳 / Lobotomy E.G.O::Tearful Blade Rodion",
    "［腦業公司 E.G.O::魔彈］奧提斯 / Lobotomy E.G.O::Magic Bullet Outis",
    "［LCE E.G.O::AEDD］格里高爾 / LCE E.G.O::AEDD Gregor",
    "［腦業公司 E.G.O::星之燈］格里高爾 / Lobotomy E.G.O::Star of the Lamp Gregor",
    "［開花E.G.O：山茶花］李箱 / Effloresced E.G.O::Camellia Yi Sang",
    "［呼嘯山莊 首席管家］奧提斯 / Wuthering Heights Chief Butler Outis",
    "［厄加家族 首席管家］良秀 / Edgar Family Chief Butler Ryōshū",
    "［厄加家族 繼承人］格里高爾 / Edgar Family Heir Gregor",
    "［皮夸德號 船長］以實瑪利 / Pequod Captain Ishmael",
    "［皮夸德號 魚叉手］希斯克里夫 / Pequod Harpooneer Heathcliff",
    "［狂獵］希斯克里夫 / Wild Hunt Heathcliff",
    "［丁當幫 老大］鴻璐 / Tingtang Gang Leader Hong Lu",
    "［宏願之主］鴻璐 / Lord of Hongyuan Hong Lu",
    "［宏願之流浪劍客］良秀 / Wandering Swordsman of Hongyuan Ryōshū",
    "［劍契 殺手］李箱 / Blade Lineage Salsu Yi Sang",
    "［劍契 殺手］浮士德 / Blade Lineage Salsu Faust",
    "［劍契 殺手］辛克萊 / Blade Lineage Salsu Sinclair",
    "［劍契 導師］默爾索 / Blade Lineage Mentor Meursault",
    "［黑雲會 組長］以實瑪利 / Kurokumo Clan Captain Ishmael",
    "［黑雲會 組長］良秀 / Kurokumo Clan Captain Ryōshū",
    "［黑雲會 組長］格里高爾 / Kurokumo Clan Captain Gregor",
    "［黑雲會 眾］希斯克里夫 / Kurokumo Clan Member Heathcliff",
    "［黑雲會 眾］羅佳 / Kurokumo Clan Member Rodion",
    "［黑雲會 眾］良秀 / Kurokumo Clan Member Ryōshū",
    "［W公司 2區 清掃人員］默爾索 / W Corp. L2 Cleanup Agent Meursault",
    "［W公司 3區 清掃人員］李箱 / W Corp. L3 Cleanup Agent Yi Sang",
    "［W公司 3區 清掃人員］良秀 / W Corp. L3 Cleanup Agent Ryōshū",
    "［W公司 3區 清掃人員］堂吉訶德 / W Corp. L3 Cleanup Agent Don Quixote",
    "［W公司 4區 清掃人員］希斯克里夫 / W Corp. L4 Cleanup Agent - CCA Heathcliff",
    "［R公司 4區 兔子組］希斯克里夫 / R Corp. 4th Pack Rabbit Heathcliff",
    "［R公司 4區 馴鹿組］以實瑪利 / R Corp. 4th Pack Reindeer Ishmael",
    "［R公司 4區 犀牛組］默爾索 / R Corp. 4th Pack Rhino Meursault",
    "［K公司 3級 剔除人員］鴻璐 / K Corp. Excision Staff Class 3 Hong Lu",
    "［T公司 3級 征收人員］堂吉訶德 / T Corp. Class 3 Collection Staff Don Quixote",
    "［G公司 下士］格里高爾 / G Corp. Corporal Gregor",
    "［N公司 執柄者］浮士德 / The One Who Grips Faust",
    "［N公司 準執柄者］辛克萊 / The One Who Shall Grip Sinclair",
    "［N公司 大錘］默爾索 / N Corp. Großhammer Meursault",
    "［七協會 南部6科 部長］奧提斯 / Seven Assoc. South Section 6 Director Outis",
    "［七協會 南部4科］浮士德 / Seven Assoc. South Section 4 Faust",
    "［六協會 南部4科 部長］羅佳 / Liu Assoc. South Section 4 Rodion",
    " [五協會 南部5科 科長] 堂吉訶德 / Cinq Assoc. South Section 5 Director Don Quixote",
    "［Cinq協會 南部5科］堂吉訶德 / Cinq Assoc. South Section 5 Don Director Quixote",
    "［Cinq協會 東部3科］堂吉訶德 / Cinq Assoc. East Section 3 Don Quixote",
    "［Cinq協會 西部3科］默爾索 / Cinq Assoc. West Section 3 Meursault",
    "［Zwei協會 西部3科］以實瑪利 / Zwei Assoc. West Section 3 Ishmael",
    "［Dieci協會 南部4科］羅佳 / Dieci Assoc. South Section 4 Rodion",
    "［Dieci協會 南部4科］鴻璐 / Dieci Assoc. South Section 4 Hong Lu",
    "［Dieci協會 南部4科］默爾索 / Dieci Assoc. South Section 4 Meursault",
    "［Devyat協會 北部3科］羅佳 / Devyat' Assoc. North Section 3 Rodion",
    "［Devyat協會 北部3科］辛克萊 / Devyat' Assoc. North Section 3 Sinclair",
    "［Öufi協會 南部3科］希斯克里夫 / Öufi Assoc. South Section 3 Heathcliff",
    "［LCA 烏加特先鋒 第三小隊 隊長］奧提斯 / LCA Udjat Vanguard Team 3 Leader Outis",
    "［黎明事務所 幫手］辛克萊 / Dawn Office Fixer Sinclair",
    "［臼齒事務所 幫手］奧提斯 / Molar Office Fixer Outis",
    "［鄭氏事務所 代理］以實瑪利 / Jeong's Office Representative Ishmael",
    "［多裂紋事務所 代理］浮士德 / Multicrack Office Representative Faust",
    "［火拳事務所 倖存者］格里高爾 / Firefist Office Survivor Gregor",
    "［雙鉤海賊團 一副］格里高爾 / Twinhook Pirates First Mate Gregor"
    "［Liu協會 南部3科］李箱 / Liu Assoc. South Section 3 Yi Sang",
    "［Liu協會 南部4科］以實瑪利 / Liu Assoc. South Section 4 Ishmael",
    "［臼齒船舶事務所 幫手］以實瑪利 / Molar Boatworks Fixer Ishmael",
    "［尤羅季維 第20區］鴻璐 / District 20 Yurodivy Hong Lu",
    "［玫瑰扳手工坊 代理］羅佳 / Rosespanner Workshop Rep Rodion",
    "［Shi協會 東部3科］浮士德 / Shi Assoc. East Section 3 Faust"
  ],

  '00': [
    "［中指 小弟］默爾索 / Middle Brother Meursault",
    "［黑雲會 眾］鴻璐 / Kurokumo Clan Member Hong Lu",
    "［LCE E.G.O::提燈］李箱 / LCE E.G.O::Lantern Yi Sang",
    "［Lobotomy E.G.O::紅符］辛克萊 / Lobotomy E.G.O::Red Sheet Sinclair",
    "［Lobotomy E.G.O::游移］以實瑪利 / Lobotomy E.G.O::Sloshing Ishmael",
    "［W公司 2區 清道夫］浮士德 / W Corp. L2 Cleanup Agent Faust",
    "［W公司 2區 清道夫］鴻璐 / W Corp. L2 Cleanup Agent Hong Lu",
    "［N公司 中錘］堂吉訶德 / N Corp. Mittelhammer Don Quixote",
    "［N公司 中錘］羅佳 / N Corp. Mittelhammer Rodion",
    "［N公司 小錘］希斯克里夫 / N Corp. Kleinhammer Heathcliff",
    "［Shi協會 南部5科 部長］堂吉訶德 / Shi Assoc. South Section 5 Director Don Quixote",
    "［Shi協會 南部5科］以實瑪利 / Shi Assoc. South Section 5 Ishmael",
    "［Shi協會 南部5科］希斯克里夫 / Shi Assoc. South Section 5 Heathcliff",
    "［Zwei協會 南部6科］辛克萊 / Zwei Assoc. South Section 6 Sinclair",
    "［Zwei協會 南部6科］格里高爾 / Zwei Assoc. South Section 6 Gregor",
    "［Zwei協會 南部4科］浮士德 / Zwei Assoc. South Section 4 Faust",
    "［Liu協會 南部6科］默爾索 / Liu Assoc. South Section 6 Meursault",
    "［Liu協會 南部6科］格里高爾 / Liu Assoc. South Section 6 Gregor",
    "［Liu協會 南部5科］鴻璐 / Liu Assoc. South Section 5 Hong Lu",
    "［Liu協會 南部4科］良秀 / Liu Assoc. South Section 4 Ryōshū",
    "［七協會 南部6科］李箱 / Seven Assoc. South Section 6 Yi Sang",
    "［七協會 南部6科］良秀 / Seven Assoc. South Section 6 Ryōshū",
    "［七協會 南部4科］希斯克里夫 / Seven Assoc. South Section 4 Heathcliff",
    "［Cinq協會 南部4科］奧提斯 / Cinq Assoc. South Section 4 Outis",
    "［呼嘯山莊 管家］浮士德 / Wuthering Heights Butler Faust",
    "［厄加家族 管家］以實瑪利 / Edgar Family Butler Ishmael",
    "［劍契 殺手］堂吉訶德 / Blade Lineage Salsu Don Quixote",
    "［劍契 殺手］奧提斯 / Blade Lineage Salsu Outis",
    "［LCCB 助理經理］以實瑪利 / LCCB Assistant Manager Ishmael",
    "［LCCB 助理經理］良秀 / LCCB Assistant Manager Ryōshū",
    "［LCCB 助理經理］羅佳 / LCCB Assistant Manager Rodion",
    "［玫瑰扳手工坊 幫手］默爾索 / Rosespanner Workshop Fixer Meursault",
    "［玫瑰扳手工坊 幫手］格里高爾 / Rosespanner Workshop Fixer Gregor",
    "［臼齒船舶事務所 幫手］辛克萊 / Molar Boatworks Fixer Sinclair",
    "［臼齒事務所 幫手］李箱 / Molar Office Fixer Yi Sang",
    "［鉤子事務所 幫手］鴻璐 / Hook Office Fixer Hong Lu",
    "［尤羅季維 第20區］良秀 / District 20 Yurodivy Ryōshū",
    "［洛斯馬利亞契 老大］辛克萊 / Los Mariachis Jefe Sinclair",
    "［死兔黨 老大］默爾索 / Dead Rabbits Boss Meursault",
    "［R.B. 副主廚］格里高爾 / R.B. Sous-chef Gregor",
    "［皮夸德號 一副］李箱 / Pequod First Mate Yi Sang",
    "［Dieci協會 南部4科］李箱 / Dieci Assoc. South Section 4 Yi Sang",
    "［G公司 科長］奧提斯 / G Corp. Head Manager Outis"
  ],

  '0': [
    "［邊獄公司 罪人］李箱 / LCB Sinner Yi Sang",
    "［邊獄公司 罪人］浮士德 / LCB Sinner Faust",
    "［邊獄公司 罪人］堂吉訶德 / LCB Sinner Don Quixote",
    "［邊獄公司 罪人］良秀 / LCB Sinner Ryōshū",
    "［邊獄公司 罪人］默爾索 / LCB Sinner Meursault",
    "［邊獄公司 罪人］希斯克里夫 / LCB Sinner Heathcliff",
    "［邊獄公司 罪人］以實瑪利 / LCB Sinner Ishmael",
    "［邊獄公司 罪人］鴻璐 / LCB Sinner Hong Lu",
    "［邊獄公司 罪人］羅佳 / LCB Sinner Rodion",
    "［邊獄公司 罪人］辛克萊 / LCB Sinner Sinclair",
    "［邊獄公司 罪人］奧提斯 / LCB Sinner Outis",
    "［邊獄公司 罪人］格里高爾 / LCB Sinner Gregor"
  ]
};

const upTargets = {
  '000': [
    "［蜘蛛巢：中指 父輩］奧提斯 / The House of Spiders: Middle Father Outis",
    "  [蜘蛛巢：中指 學徒］以實瑪利 / House of Spiders: Middle Apprentice Ishmael"
  ],
  '00': [
    "［中指 小弟］默爾索 / Middle Brother Meursault",
  ],
  '0': []
};

function pullIdentity(rarity) {
  const pool = identities[rarity] || [];
  if (!pool.length) return '（該稀有度沒有資料）';
  return pool[Math.floor(Math.random() * pool.length)];
}

function pullUpIdentity(rarity) {
  const pool = upTargets[rarity] || [];
  if (!pool.length) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

module.exports = {
  identities,
  upTargets,
  pullIdentity,
  pullUpIdentity
};
