// Functions/GameSystem/MusicSystem.js
    'use strict';
    const play=require('play-dl');
    const {joinVoiceChannel,createAudioPlayer,createAudioResource,AudioPlayerStatus,NoSubscriberBehavior,StreamType}=require('@discordjs/voice');
    const queues=new Map();
    const RESOLVE_TIMEOUT_MS=20000;
    const STREAM_TIMEOUT_MS=20000;
    function withTimeout(promise,ms,label){let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(label+'逾時，請稍後再試。')),ms);});return Promise.race([promise,timeout]).finally(()=>clearTimeout(timer));}
    const isYoutubePlaylist=url=>/(youtube\.com|youtu\.be)/i.test(url)&&/[?&]list=/i.test(url);
    const makeTrack=(x,source)=>({url:x.url,title:x.title||x.name||x.name_raw||'未命名歌曲',source});
    async function resolve(url){if(/open\.spotify\.com\/(track|album|playlist)/i.test(url))throw new Error('目前不支援 Spotify 連結；請改用 YouTube 或 SoundCloud 連結（不需要 API）。');if(isYoutubePlaylist(url)){const p=await withTimeout(play.playlist_info(url,{incomplete:true}),RESOLVE_TIMEOUT_MS,'YouTube 播放清單讀取');return (await withTimeout(p.all_videos(),RESOLVE_TIMEOUT_MS,'YouTube 播放清單讀取')).slice(0,100).map(x=>makeTrack(x,'YouTube')).filter(x=>x.url);}if(/soundcloud\.com/i.test(url)){const item=await withTimeout(play.soundcloud(url),RESOLVE_TIMEOUT_MS,'SoundCloud 連結讀取');if(typeof item.all_tracks==='function')return (await withTimeout(item.all_tracks(),RESOLVE_TIMEOUT_MS,'SoundCloud 播放清單讀取')).slice(0,100).map(x=>makeTrack(x,'SoundCloud')).filter(x=>x.url);return [makeTrack(item,'SoundCloud')];}return [makeTrack((await withTimeout(play.video_basic_info(url),RESOLVE_TIMEOUT_MS,'YouTube 連結讀取')).video_details,'YouTube')];}
    async function next(guildId){const q=queues.get(guildId);if(!q||!q.tracks.length){queues.delete(guildId);return;}const t=q.tracks.shift();try{const s=await withTimeout(play.stream(t.url),STREAM_TIMEOUT_MS,'音訊串流'),r=createAudioResource(s.stream,{inputType:s.type||StreamType.WebmOpus,inlineVolume:true});r.volume?.setVolume(.8);q.player.play(r);await q.text.send('▶️ 正在播放：**'+t.title+'**（'+t.source+'）').catch(()=>{});}catch(err){await q.text.send('⚠️ 無法播放 **'+t.title+'**，已跳過。').catch(()=>{});return next(guildId);}}
    async function handlePlay(client,interaction){const voice=interaction.member?.voice?.channel;if(!voice)return interaction.reply({content:'❌ 你必須先加入一個語音頻道。',ephemeral:true});const url=interaction.options.getString('musiclink',true).trim();await interaction.deferReply();let tracks;try{tracks=await resolve(url);}catch(err){return interaction.editReply('❌ 讀取音樂連結失敗：'+err.message.slice(0,1200));}if(!tracks.length)return interaction.editReply('❌ 找不到可播放的曲目。');let q=queues.get(interaction.guild.id);if(!q){const connection=joinVoiceChannel({channelId:voice.id,guildId:interaction.guild.id,adapterCreator:interaction.guild.voiceAdapterCreator}),player=createAudioPlayer({behaviors:{noSubscriber:NoSubscriberBehavior.Play}});connection.subscribe(player);q={connection,player,tracks:[],text:interaction.channel};queues.set(interaction.guild.id,q);player.on(AudioPlayerStatus.Idle,()=>next(interaction.guild.id));player.on('error',err=>interaction.channel.send('⚠️ 播放器錯誤：'+err.message.slice(0,300)).catch(()=>{}));}q.text=interaction.channel;q.tracks.push(...tracks);if(q.player.state.status===AudioPlayerStatus.Idle)await next(interaction.guild.id);return interaction.editReply('✅ 已加入 **'+tracks.length+'** 首歌曲到播放佇列。'+(tracks.length>1?' 播放清單會依序播放。':''));}
    function stop(guildId){const q=queues.get(guildId);if(!q)return;q.player.stop(true);queues.delete(guildId);}
    module.exports={handlePlay,stop};
    